export interface MeditationTrackConfig {
  id: string;
  sessionId: 'calm-10' | 'focus-15' | 'sleep-20';
  src: string;
  minutes: number;
  theme: 'stress' | 'sleep' | 'focus' | 'recovery';
  titleKey: string;
  descKey: string;
  tagKeys: string[];
  coverGradient: string;
  sourceName: string;
  sourceUrl: string;
  licenseType: string;
  attributionKey: string;
}

// Frontend-configured playlist with licensing metadata and localized copy.
export const meditationPlaylist: MeditationTrackConfig[] = [
  {
    id: 'stress-calm-reset-10',
    sessionId: 'calm-10',
    src: '/audio/meditation/calm-reset.m4a',
    minutes: 10,
    theme: 'stress',
    titleKey: 'tools.meditation_tracks.stress_calm_reset_10.title',
    descKey: 'tools.meditation_tracks.stress_calm_reset_10.desc',
    tagKeys: ['tools.meditation_tags.stress_relief', 'tools.meditation_tags.breath_sync', 'tools.meditation_tags.quick_recovery'],
    coverGradient: 'linear-gradient(135deg, #2dd4bf 0%, #0f766e 100%)',
    sourceName: 'Pixabay Music (A01)',
    sourceUrl: 'https://pixabay.com/service/license-summary/',
    licenseType: 'Pixabay License',
    attributionKey: 'tools.meditation_attr.pixabay_no_attribution',
  },
  {
    id: 'stress-soft-reset-8',
    sessionId: 'calm-10',
    src: '/audio/meditation/calm-reset-soft-8.m4a',
    minutes: 8,
    theme: 'stress',
    titleKey: 'tools.meditation_tracks.stress_soft_reset_8.title',
    descKey: 'tools.meditation_tracks.stress_soft_reset_8.desc',
    tagKeys: ['tools.meditation_tags.quick_recovery', 'tools.meditation_tags.low_stimulation', 'tools.meditation_tags.breath_sync'],
    coverGradient: 'linear-gradient(135deg, #67e8f9 0%, #0891b2 100%)',
    sourceName: 'Pixabay Music (A01)',
    sourceUrl: 'https://pixabay.com/service/license-summary/',
    licenseType: 'Pixabay License',
    attributionKey: 'tools.meditation_attr.pixabay_no_attribution',
  },
  {
    id: 'stress-evening-release-12',
    sessionId: 'calm-10',
    src: '/audio/meditation/calm-reset-evening-12.m4a',
    minutes: 12,
    theme: 'stress',
    titleKey: 'tools.meditation_tracks.stress_evening_release_12.title',
    descKey: 'tools.meditation_tracks.stress_evening_release_12.desc',
    tagKeys: ['tools.meditation_tags.after_work', 'tools.meditation_tags.stress_relief', 'tools.meditation_tags.sleep_aid'],
    coverGradient: 'linear-gradient(135deg, #5eead4 0%, #0f766e 100%)',
    sourceName: 'Pixabay Music (A01)',
    sourceUrl: 'https://pixabay.com/service/license-summary/',
    licenseType: 'Pixabay License',
    attributionKey: 'tools.meditation_attr.pixabay_no_attribution',
  },
  {
    id: 'focus-grounding-15',
    sessionId: 'focus-15',
    src: '/audio/meditation/focus-grounding.m4a',
    minutes: 15,
    theme: 'focus',
    titleKey: 'tools.meditation_tracks.focus_grounding_15.title',
    descKey: 'tools.meditation_tracks.focus_grounding_15.desc',
    tagKeys: ['tools.meditation_tags.focus', 'tools.meditation_tags.task_launch', 'tools.meditation_tags.anti_distraction'],
    coverGradient: 'linear-gradient(135deg, #38bdf8 0%, #1d4ed8 100%)',
    sourceName: 'Mixkit (A03)',
    sourceUrl: 'https://mixkit.co/free-stock-music/',
    licenseType: 'Mixkit Free License',
    attributionKey: 'tools.meditation_attr.mixkit_no_attribution',
  },
  {
    id: 'focus-deepwork-12',
    sessionId: 'focus-15',
    src: '/audio/meditation/focus-deepwork-12.m4a',
    minutes: 12,
    theme: 'focus',
    titleKey: 'tools.meditation_tracks.focus_deepwork_12.title',
    descKey: 'tools.meditation_tracks.focus_deepwork_12.desc',
    tagKeys: ['tools.meditation_tags.pre_pomodoro', 'tools.meditation_tags.execution', 'tools.meditation_tags.focus'],
    coverGradient: 'linear-gradient(135deg, #7dd3fc 0%, #2563eb 100%)',
    sourceName: 'Mixkit (A03)',
    sourceUrl: 'https://mixkit.co/license/',
    licenseType: 'Mixkit Free License',
    attributionKey: 'tools.meditation_attr.mixkit_no_attribution',
  },
  {
    id: 'focus-breath-align-9',
    sessionId: 'focus-15',
    src: '/audio/meditation/focus-breath-9.m4a',
    minutes: 9,
    theme: 'focus',
    titleKey: 'tools.meditation_tracks.focus_breath_align_9.title',
    descKey: 'tools.meditation_tracks.focus_breath_align_9.desc',
    tagKeys: ['tools.meditation_tags.breath_sync', 'tools.meditation_tags.focus', 'tools.meditation_tags.task_launch'],
    coverGradient: 'linear-gradient(135deg, #22d3ee 0%, #1e40af 100%)',
    sourceName: 'Mixkit (A03)',
    sourceUrl: 'https://mixkit.co/free-stock-music/',
    licenseType: 'Mixkit Free License',
    attributionKey: 'tools.meditation_attr.mixkit_no_attribution',
  },
  {
    id: 'sleep-winddown-20',
    sessionId: 'sleep-20',
    src: '/audio/meditation/sleep-winddown.m4a',
    minutes: 20,
    theme: 'sleep',
    titleKey: 'tools.meditation_tracks.sleep_winddown_20.title',
    descKey: 'tools.meditation_tracks.sleep_winddown_20.desc',
    tagKeys: ['tools.meditation_tags.sleep', 'tools.meditation_tags.ambient', 'tools.meditation_tags.sleep_aid'],
    coverGradient: 'linear-gradient(135deg, #a78bfa 0%, #4338ca 100%)',
    sourceName: 'Incompetech (A05)',
    sourceUrl: 'https://music.kevin.macleod.incompetech.com/',
    licenseType: 'CC BY 4.0 / Licensed Track',
    attributionKey: 'tools.meditation_attr.incompetech_credit_note',
  },
  {
    id: 'sleep-bodyscan-15',
    sessionId: 'sleep-20',
    src: '/audio/meditation/sleep-body-scan-15.m4a',
    minutes: 15,
    theme: 'sleep',
    titleKey: 'tools.meditation_tracks.sleep_bodyscan_15.title',
    descKey: 'tools.meditation_tracks.sleep_bodyscan_15.desc',
    tagKeys: ['tools.meditation_tags.body_scan', 'tools.meditation_tags.sleep_aid', 'tools.meditation_tags.sleep'],
    coverGradient: 'linear-gradient(135deg, #c4b5fd 0%, #4f46e5 100%)',
    sourceName: 'Incompetech (A05)',
    sourceUrl: 'https://web.incompetech.com/music/royalty-free/licenses/retail.php',
    licenseType: 'CC BY 4.0 / Retail License',
    attributionKey: 'tools.meditation_attr.incompetech_retail_note',
  },
  {
    id: 'sleep-night-rain-20',
    sessionId: 'sleep-20',
    src: '/audio/meditation/sleep-night-rain-20.m4a',
    minutes: 20,
    theme: 'sleep',
    titleKey: 'tools.meditation_tracks.sleep_night_rain_20.title',
    descKey: 'tools.meditation_tracks.sleep_night_rain_20.desc',
    tagKeys: ['tools.meditation_tags.ambient', 'tools.meditation_tags.sleep', 'tools.meditation_tags.sleep_aid'],
    coverGradient: 'linear-gradient(135deg, #818cf8 0%, #312e81 100%)',
    sourceName: 'Incompetech (A05)',
    sourceUrl: 'https://music.kevin.macleod.incompetech.com/',
    licenseType: 'CC BY 4.0 / Licensed Track',
    attributionKey: 'tools.meditation_attr.incompetech_credit_note',
  },
  {
    id: 'recovery-somatic-10',
    sessionId: 'calm-10',
    src: '/audio/meditation/recovery-somatic-10.m4a',
    minutes: 10,
    theme: 'recovery',
    titleKey: 'tools.meditation_tracks.recovery_somatic_10.title',
    descKey: 'tools.meditation_tracks.recovery_somatic_10.desc',
    tagKeys: ['tools.meditation_tags.recovery', 'tools.meditation_tags.stress_relief', 'tools.meditation_tags.quick_recovery'],
    coverGradient: 'linear-gradient(135deg, #5eead4 0%, #0f766e 100%)',
    sourceName: 'Pixabay Music (A01)',
    sourceUrl: 'https://pixabay.com/service/license-summary/',
    licenseType: 'Pixabay License',
    attributionKey: 'tools.meditation_attr.pixabay_no_attribution',
  },
  {
    id: 'recovery-clarity-11',
    sessionId: 'focus-15',
    src: '/audio/meditation/recovery-clarity-11.m4a',
    minutes: 11,
    theme: 'recovery',
    titleKey: 'tools.meditation_tracks.recovery_clarity_11.title',
    descKey: 'tools.meditation_tracks.recovery_clarity_11.desc',
    tagKeys: ['tools.meditation_tags.recovery', 'tools.meditation_tags.focus', 'tools.meditation_tags.resilience'],
    coverGradient: 'linear-gradient(135deg, #67e8f9 0%, #1d4ed8 100%)',
    sourceName: 'Mixkit (A03)',
    sourceUrl: 'https://mixkit.co/free-stock-music/',
    licenseType: 'Mixkit Free License',
    attributionKey: 'tools.meditation_attr.mixkit_no_attribution',
  },
  {
    id: 'recovery-gentle-14',
    sessionId: 'sleep-20',
    src: '/audio/meditation/recovery-gentle-14.m4a',
    minutes: 14,
    theme: 'recovery',
    titleKey: 'tools.meditation_tracks.recovery_gentle_14.title',
    descKey: 'tools.meditation_tracks.recovery_gentle_14.desc',
    tagKeys: ['tools.meditation_tags.recovery', 'tools.meditation_tags.sleep_aid', 'tools.meditation_tags.resilience'],
    coverGradient: 'linear-gradient(135deg, #c4b5fd 0%, #3730a3 100%)',
    sourceName: 'Incompetech (A05)',
    sourceUrl: 'https://web.incompetech.com/music/royalty-free/licenses/retail.php',
    licenseType: 'CC BY 4.0 / Retail License',
    attributionKey: 'tools.meditation_attr.incompetech_retail_note',
  },
];
